# Generated by Django 6.0.6 on 2026-07-07 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_load_initial_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='posted_to_bluesky',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='posted_to_mastodon',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='share_to_bluesky',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='share_to_mastodon',
        ),
    ]
