# Generated by Django 6.0.6 on 2026-07-07 20:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_pageasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='logentry',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='Indicates if email was already sent for this entry.'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='send_email_notification',
            field=models.BooleanField(default=False, help_text='Send email newsletter to all subscribers on save.'),
        ),
    ]
